name: mol-inspector
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pip
  - pip:
      - notebook==7.0.6
      - ipywidgets
      - shap
      - keras
      - xgboost
      - torch
      - seaborn
      - rdkit
#      - exmol # for future use
